### ISSUE TITLE
Mapa Mental_DiegoFidelSosaCruz

### ISSUE THREAD

**Issue by ghost** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Diego0501#2]
[Diego Sosa_Conjuntos Funciones y Relaciones.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Diego0501/files/12679745/Diego.Sosa_Conjuntos.Funciones.y.Relaciones.pdf)

**Comment by 23620031** [comment]
MANEJO CONCEPTUAL Y DOMINIO DEL TEMA-> 25/25
RELACIÓN ENTRE LOS CONCEPTOS EN EL MAPA-> 25/25
CALIDAD DE LA PRESENTACIÓN-> 25/25
JERARQUIZACIÓN DE IDEAS-> 25/25

TOTAL=20/20

CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
